apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: python-a-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-a-db
  labels:
    app: python-a-db
    service: python-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-a-db
      service: python-a
  template:
    metadata:
      labels:
        app: python-a-db
        service: python-a
    spec:
      serviceAccountName: python-a-db
      volumes:
      - name: python-a-db-volume
        persistentVolumeClaim:
          claimName: python-a-db
      containers:
      - name: python-a-db-container
        image: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: python-a-db-volume
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: "pass123"