apiVersion: v1
kind: Service
metadata:
  name: python-a-db
  labels:
    app: python-a-db
    service: python-a
spec:
  selector:
    app: python-a-db
    service: python-a
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP