apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: python-a

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-a
  labels:
    app: python-a
    service: python-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-a
      service: python-a
  template:
    metadata:
      labels:
        app: python-a
        service: python-a
    spec:
      serviceAccountName: python-a
      
      containers:
      - name: python-a-container
        image: hhana982/python-a:1.<version>
        ports:
        - containerPort: 5000
        
        env: 